# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/energyui/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAuth(object):
    def setupUi(self, DialogAuth):
        DialogAuth.setObjectName("DialogAuth")
        DialogAuth.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogAuth.resize(382, 257)
        DialogAuth.setModal(True)
        self.pushButtonLogIn = QtWidgets.QPushButton(DialogAuth)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(80, 160, 81, 24))
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.pushButtonRegister = QtWidgets.QPushButton(DialogAuth)
        self.pushButtonRegister.setGeometry(QtCore.QRect(200, 160, 81, 24))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.lineEditPass = QtWidgets.QLineEdit(DialogAuth)
        self.lineEditPass.setGeometry(QtCore.QRect(80, 120, 201, 22))
        self.lineEditPass.setObjectName("lineEditPass")
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditLogin = QtWidgets.QLineEdit(DialogAuth)
        self.lineEditLogin.setGeometry(QtCore.QRect(80, 60, 201, 22))
        self.lineEditLogin.setObjectName("lineEditLogin")

        self.retranslateUi(DialogAuth)
        QtCore.QMetaObject.connectSlotsByName(DialogAuth)



    def retranslateUi(self, DialogAuth):
        _translate = QtCore.QCoreApplication.translate
        DialogAuth.setWindowTitle(_translate("DialogAuth", "Авторизация"))
        self.pushButtonLogIn.setText(_translate("DialogAuth", "Войти"))
        self.pushButtonRegister.setText(_translate("DialogAuth", "Регистрация"))
        self.lineEditPass.setPlaceholderText(_translate("DialogAuth", "Пароль..."))
        self.lineEditLogin.setPlaceholderText(_translate("DialogAuth", "Логин..."))
